#!/bin/sh -e

for i in ftp pagsh
do
    update-alternatives --install /usr/bin/$i $i /usr/bin/k$i 23 \
    --slave /usr/share/man/man1/$i.1.gz $i.1.gz /usr/share/man/man1/k$i.1.gz
done

for i in kinit klist kswitch ksu kpasswd kdestroy kadmin ktutil
do
    update-alternatives --install /usr/bin/$i $i /usr/bin/${i}.heimdal 23 \
    --slave /usr/share/man/man1/${i}.1.gz ${i}.1.gz /usr/share/man/man1/${i}.heimdal.1.gz
done

#DEBHELPER#

